name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
          lfs: true # Fetch Git LFS files

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # 🛑 REPLACE THESE VARIABLES with your Hugging Face details
          HF_USERNAME: "Gauurab"
          SPACE_NAME: "chips-counter"
        run: |
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          git push --force space main
